///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SomeRootEntityCities {
/*
{
  "name": "Rome",
  "description": "Rome, the capital city of Italy, is a vibrant blend of history, art, and culture. Visit the iconic Colosseum, the Roman Forum, and the Vatican City. Indulge in delicious Italian cuisine, explore charming piazzas, and toss a coin in the Trevi Fountain for good luck.",
  "map_link": "Google Maps link placeholder",
  "beautiful_places": [
    "Colosseum"
  ],
  "average_flight_cost_from_Istanbul": 150,
  "average_accommodation_cost_per_night": 100
}
*/

  String? name;
  String? description;
  String? mapLink;
  List<String>? beautifulPlaces;
  int? averageFlightCostFromIstanbul;
  int? averageAccommodationCostPerNight;

  SomeRootEntityCities({
    this.name,
    this.description,
    this.mapLink,
    this.beautifulPlaces,
    this.averageFlightCostFromIstanbul,
    this.averageAccommodationCostPerNight,
  });
  SomeRootEntityCities.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    description = json['description']?.toString();
    mapLink = json['map_link']?.toString();
    if (json['beautiful_places'] != null) {
      final v = json['beautiful_places'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      beautifulPlaces = arr0;
    }
    averageFlightCostFromIstanbul = json['average_flight_cost_from_Istanbul']?.toInt();
    averageAccommodationCostPerNight = json['average_accommodation_cost_per_night']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['description'] = description;
    data['map_link'] = mapLink;
    if (beautifulPlaces != null) {
      final v = beautifulPlaces;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v);
      });
      data['beautiful_places'] = arr0;
    }
    data['average_flight_cost_from_Istanbul'] = averageFlightCostFromIstanbul;
    data['average_accommodation_cost_per_night'] = averageAccommodationCostPerNight;
    return data;
  }
}

class SomeRootEntity {
/*
{
  "cities": [
    {
      "name": "Rome",
      "description": "Rome, the capital city of Italy, is a vibrant blend of history, art, and culture. Visit the iconic Colosseum, the Roman Forum, and the Vatican City. Indulge in delicious Italian cuisine, explore charming piazzas, and toss a coin in the Trevi Fountain for good luck.",
      "map_link": "Google Maps link placeholder",
      "beautiful_places": [
        "Colosseum"
      ],
      "average_flight_cost_from_Istanbul": 150,
      "average_accommodation_cost_per_night": 100
    }
  ]
}
*/

  List<SomeRootEntityCities>? cities;

  SomeRootEntity({
    this.cities,
  });
  SomeRootEntity.fromJson(Map<String, dynamic> json) {
    if (json['cities'] != null) {
      final v = json['cities'];
      final arr0 = <SomeRootEntityCities>[];
      v.forEach((v) {
        arr0.add(SomeRootEntityCities.fromJson(v));
      });
      cities = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (cities != null) {
      final v = cities;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['cities'] = arr0;
    }
    return data;
  }
}
