///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class SomeRootEntityDataHotelsProperty {
/*
{
  "reviewScoreWord": "Superb",
  "accuratePropertyClass": 5,
  "reviewCount": 4887,
  "reviewScore": 9,
  "countryCode": "in",
  "propertyClass": 5,
  "photoUrls": [
    "https://cf.bstatic.com/xdata/images/hotel/square60/31204963.jpg?k=90c11832231c37a814e9631123bd28820e8ad8cd983b78ad529ea139791653d1&o="
  ],
  "latitude": 18.9215006738599,
  "currency": "INR",
  "checkinDate": "2023-11-21",
  "id": 74717,
  "mainPhotoId": 31204963,
  "name": "The Taj Mahal Tower, Mumbai",
  "longitude": 72.8332896530628
}
*/

  String? reviewScoreWord;
  int? accuratePropertyClass;
  int? reviewCount;
  int? reviewScore;
  String? countryCode;
  int? propertyClass;
  List<String>? photoUrls;
  double? latitude;
  String? currency;
  String? checkInDate;
  int? id;
  int? mainPhotoId;
  String? name;
  double? longitude;

  SomeRootEntityDataHotelsProperty({
    this.reviewScoreWord,
    this.accuratePropertyClass,
    this.reviewCount,
    this.reviewScore,
    this.countryCode,
    this.propertyClass,
    this.photoUrls,
    this.latitude,
    this.currency,
    this.checkInDate,
    this.id,
    this.mainPhotoId,
    this.name,
    this.longitude,
  });

  SomeRootEntityDataHotelsProperty.fromJson(Map<String, dynamic> json) {
    reviewScoreWord = json['reviewScoreWord']?.toString();
    accuratePropertyClass = json['accuratePropertyClass']?.toInt();
    reviewCount = json['reviewCount']?.toInt();
    reviewScore = json['reviewScore']?.toInt();
    countryCode = json['countryCode']?.toString();
    propertyClass = json['propertyClass']?.toInt();
    if (json['photoUrls'] != null) {
      final v = json['photoUrls'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      photoUrls = arr0;
    }
    latitude = json['latitude']?.toDouble();
    currency = json['currency']?.toString();
    checkInDate = json['checkinDate']?.toString();
    id = json['id']?.toInt();
    mainPhotoId = json['mainPhotoId']?.toInt();
    name = json['name']?.toString();
    longitude = json['longitude']?.toDouble();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['reviewScoreWord'] = reviewScoreWord;
    data['accuratePropertyClass'] = accuratePropertyClass;
    data['reviewCount'] = reviewCount;
    data['reviewScore'] = reviewScore;
    data['countryCode'] = countryCode;
    data['propertyClass'] = propertyClass;
    if (photoUrls != null) {
      final v = photoUrls;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v);
      });
      data['photoUrls'] = arr0;
    }
    data['latitude'] = latitude;
    data['currency'] = currency;
    data['checkinDate'] = checkInDate;
    data['id'] = id;
    data['mainPhotoId'] = mainPhotoId;
    data['name'] = name;
    data['longitude'] = longitude;
    return data;
  }
}

class SomeRootEntityDataHotels {
/*
{
  "property": {
    "reviewScoreWord": "Superb",
    "accuratePropertyClass": 5,
    "reviewCount": 4887,
    "reviewScore": 9,
    "countryCode": "in",
    "propertyClass": 5,
    "photoUrls": [
      "https://cf.bstatic.com/xdata/images/hotel/square60/31204963.jpg?k=90c11832231c37a814e9631123bd28820e8ad8cd983b78ad529ea139791653d1&o="
    ],
    "latitude": 18.9215006738599,
    "currency": "INR",
    "checkinDate": "2023-11-21",
    "id": 74717,
    "mainPhotoId": 31204963,
    "name": "The Taj Mahal Tower, Mumbai",
    "longitude": 72.8332896530628
  }
}
*/

  SomeRootEntityDataHotelsProperty? property;

  SomeRootEntityDataHotels({
    this.property,
  });

  SomeRootEntityDataHotels.fromJson(Map<String, dynamic> json) {
    property = (json['property'] != null)
        ? SomeRootEntityDataHotelsProperty.fromJson(json['property'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (property != null) {
      data['property'] = property?.toJson();
    }
    return data;
  }
}

class SomeRootEntityData {
/*
{
  "hotels": [
    {
      "property": {
        "reviewScoreWord": "Superb",
        "accuratePropertyClass": 5,
        "reviewCount": 4887,
        "reviewScore": 9,
        "countryCode": "in",
        "propertyClass": 5,
        "photoUrls": [
          "https://cf.bstatic.com/xdata/images/hotel/square60/31204963.jpg?k=90c11832231c37a814e9631123bd28820e8ad8cd983b78ad529ea139791653d1&o="
        ],
        "latitude": 18.9215006738599,
        "currency": "INR",
        "checkinDate": "2023-11-21",
        "id": 74717,
        "mainPhotoId": 31204963,
        "name": "The Taj Mahal Tower, Mumbai",
        "longitude": 72.8332896530628
      }
    }
  ]
}
*/

  List<SomeRootEntityDataHotels>? hotels;

  SomeRootEntityData({
    this.hotels,
  });

  SomeRootEntityData.fromJson(Map<String, dynamic> json) {
    if (json['hotels'] != null) {
      final v = json['hotels'];
      final arr0 = <SomeRootEntityDataHotels>[];
      v.forEach((v) {
        arr0.add(SomeRootEntityDataHotels.fromJson(v));
      });
      hotels = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (hotels != null) {
      final v = hotels;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['hotels'] = arr0;
    }
    return data;
  }
}
